#!/bin/sh
#/ Usage: cbk-pull-pinboard
#/ Download all bookmarks from pinboard.in and store them in git.
set -e

cd $(dirname "$0")/../..
. share/cbk/cbk-config

if [ -z "$CBK_PINBOARD_TOKEN" ]; then
    abort "Pinboard API token missing. Get one at https://pinboard.in/settings/" \
        "password and set CBK_PINBOARD_TOKEN."
fi

test -d "$CBK_PINBOARD_DIR" || mkdir "$CBK_PINBOARD_DIR"

curl -s "https://api.pinboard.in/v1/posts/all?auth_token=${CBK_PINBOARD_TOKEN}" >\
"${CBK_PINBOARD_DIR}/bookmarks.xml"

cbk-git-commit "$0" "$CBK_PINBOARD_DIR"
