#!/bin/sh
#/ Usage: cbk-pull-irclogs
set -e

test -z "$CBK_IRCLOGS_SOURCE" &&
abort "CBK_IRCLOGS_SOURCE not set"

# Copy the log files
rsync -avz "$CBK_IRCLOGS_SOURCE/" "$CBK_IRCLOGS_DIR/"

# Commit changes to the git repository
cbk-git-commit "$0" "$CBK_IRCLOGS_DIR"
