#!/bin/sh
#/ Usage: . cbk-config
#/ Configuration, setup, and utility functions for all cbk commands.
set -eu

# Current version. This is returned by 'cbk-pull --version'
CBK_VERSION="$(cat share/cbk/version)"
export CBK_VERSION

# Add porcelain utilities to the PATH
PATH="$(pwd)/share/cbk:$PATH"
export PATH

# The base directory for all cloud backups
: "${CBK_DATA_DIR:="/data"}"

# The location of the configuration file
: "${CBK_CONFIG:="/etc/cbk.conf"}"

# Source in configuration file when present
test -f "$CBK_CONFIG" && . "$CBK_CONFIG"

# List of supported sources
: "${CBK_CLOUDS="github fastmail-imap fastmail-carddav irclogs pinboard soundcloud-likes"}"

# The locations of the individual backup data directories
: "${CBK_FASTMAIL_IMAP_DIR:="${CBK_DATA_DIR}/fastmail-imap"}"
: "${CBK_FASTMAIL_CARDDAV_DIR:="${CBK_DATA_DIR}/fastmail-carddav"}"
: "${CBK_GITHUB_DIR:="${CBK_DATA_DIR}/github"}"
: "${CBK_IRCLOGS_DIR:="${CBK_DATA_DIR}/irclogs"}"
: "${CBK_PINBOARD_DIR:="${CBK_DATA_DIR}/pinboard"}"
: "${CBK_SOUNDCLOUD_LIKES_DIR:="${CBK_DATA_DIR}/soundcloud-likes"}"
export CBK_FASTMAIL_IMAP_DIR \
    CBK_FASTMAIL_CARDDAV_DIR \
    CBK_GITHUB_DIR \
    CBK_IRCLOGS_DIR \
    CBK_PINBOARD_DIR \
    CBK_SOUNDCLOUD_LIKES_DIR

# Fingerprint of Fastmail's IMAP server SSL certificate
: "${CBK_FASTMAIL_CERT_FINGERPRINT:="958b1601563aef92607a41eb5bad22e3cace8431"}"
export CBK_FASTMAIL_CERT_FINGERPRINT

# Show usage for --help or -h
for arg in "$@"; do
    if test "$arg" = "--help" || test "$arg" = "-h"
    then
        grep '^#/' "$0" | cut -c4-
        exit 2
    fi
done

abort() {
    echo "$(basename "$0"): $*" 1>&2
    exit 1
}

true
