#!/bin/sh
#/ Usage: cbk-pull-github
#/ Mirror all GitHub repositories accessible by the configured user and token.
set -eu

cd "$(dirname "$0")/../.."
. share/cbk/cbk-config

# Ensure the base github directory exists
test -d "$CBK_GITHUB_DIR" || mkdir "$CBK_GITHUB_DIR"

# Make sure the auth credentials for the GitHub API are set
test -z "$CBK_GITHUB_USER" && abort "CBK_GITHUB_USER not set"
test -z "$CBK_GITHUB_TOKEN" && abort "CBK_GITHUB_TOKEN not set"

# Iterate over all repositories this set of credentials has access to
cbk-github-repos "$CBK_GITHUB_USER" "$CBK_GITHUB_TOKEN" |
while read line
do
    giturl="$line"
    user="$(echo "$giturl" | cut -d"/" -f4)"
    repo="$(
        echo "$giturl" |
        cut -d"/" -f5 |
        sed -e "s/.git$//g"
    )"
    repodir="$CBK_GITHUB_DIR/$user/$repo.git"
    cloneurl="https://$CBK_GITHUB_USER:$CBK_GITHUB_TOKEN@github.com/$user/$repo"

    # Skip mirroring if the repository is included in the exclude list
    skip=false
    for exclude in $CBK_GITHUB_EXCLUDES
    do
        if printf "%s/%s" "$user" "$repo" | grep -q "$exclude"
        then
            skip=true
            break
        fi
    done

    if $skip
    then
        echo "at=skip source=github git=$giturl dir=$repodir" 1>&2
        continue
    else
        echo "at=mirror source=github git=$giturl dir=$repodir" 1>&2
        cbk-git-mirror "$cloneurl" "$repodir"
    fi
done
