#!/bin/sh
#/ Usage: cbk-pull-soundcloud-likes
#/ Download all audio tracks liked by the configured user on SoundCloud.

test -z "$CBK_SOUNDCLOUD_LIKES_USER" &&
abort "CBK_SOUNDCLOUD_LIKES_USER not set"

youtube-dl \
    -q \
    -i \
    -o "${CBK_SOUNDCLOUD_LIKES_DIR}/%(uploader)s/%(id)s.%(ext)s" \
    --restrict-filenames \
    --write-info-json \
    --write-thumbnail \
    --add-metadata \
    "https://soundcloud.com/${CBK_SOUNDCLOUD_LIKES_USER}/likes"
