#!/bin/sh
set -e

cd $(dirname "$0")/../..
. share/cbk/cbk-config

# Make sure the vdirsyncer executable is available
if [ ! -x "$CBK_VDIRSYNCER_DIR/bin/vdirsyncer" ]; then
    echo "at=error command=cbk-pull-fastmail-carddav" \
        "msg=\"vdirsyncer executable not found\"" 1>&2
    exit 1
fi

# Write configuration to a temporary file and tell vdirsyncer to use it
VDIRSYNCER_CONFIG="$(mktemp -t vdirsyncerXXXX)"
trap "rm -f $VDIRSYNCER_CONFIG" EXIT
export VDIRSYNCER_CONFIG

# Fastmail requires using username in the form of user+Default@fastmail.fm to
# access CardDAV data.
#
# See https://www.fastmail.com/help/technical/servernamesandports.html#contacts
username="$(
    echo "$CBK_FASTMAIL_USERNAME" |
    sed -e "s/\(.*\)@/\1+Default@/g"
)"

cat > "$VDIRSYNCER_CONFIG" <<EOS
[general]
status_path = ~/.vdirsyncer/status/

# CARDDAV
[pair contacts]
a = carddav_local
b = carddav_remote

conflict_resolution = "b wins"

[storage carddav_local]
type = filesystem
path = ${CBK_FASTMAIL_CARDDAV_DIR}/
fileext = .vcf
encoding = utf-8

[storage carddav_remote]
type = carddav
url = https://carddav.messagingengine.com/dav/addressbooks/user/${CBK_FASTMAIL_USERNAME}/Default
auth = guess
read_only = true
username = $username
password = ${CBK_FASTMAIL_PASSWORD}
EOS

# Put the vdirsyncer executable in our PATH
PATH="$CBK_VDIRSYNCER_DIR/bin:$PATH"

# Pull down CardDAV data from the remote
vdirsyncer sync

# Commit changes to the git repository.
cbk-git-commit "$0" "$CBK_FASTMAIL_CARDDAV_DIR"
