#!/bin/sh
#/ Usage: cbk-git-mirror <repository> <directory>
#/
#/ Mirror the given git URL into the given directory, setting up the destination
#/ repository if necessary before pulling in changes from the remote.
set -eu

cd "$(dirname "$0")/../.."
. share/cbk/cbk-config

repourl="$1"
destdir="$2"

# perform the initial clone if the mirror doesn't exist yet
test -d "$destdir" ||
git clone -q --mirror "$repourl" "$destdir">/dev/null

# sync changes from the remote repository
git --git-dir="$destdir" fetch -ap --quiet "$repourl"

# optimize repository
cbk-git-gc "$destdir"
