#!/bin/sh
#/ Usage: cbk-pull-fastmail-carddav
#/ Download CardDAV (contact data) from the Fastmail server onto a local
#/ directory versioned in git. This requires vdirsyncer.
set -eu

cd "$(dirname "$0")/../.."
. share/cbk/cbk-config

# Bail out if vdirsyncer is not available on the PATH
if ! command -v "vdirsyncer">/dev/null
then
    echo "$(basename "$0"): vdirsyncer command not found" 1>&2
    exit 1
fi

# Fastmail requires using username in the form of user+Default@fastmail.fm to
# access CardDAV data.
#
# See https://www.fastmail.com/help/technical/servernamesandports.html#contacts
username="$(
    echo "$CBK_FASTMAIL_USERNAME" |
    sed -e "s/\(.*\)@/\1+Default@/g"
)"

# Write vdirsyncer config to a temporary file

VDIRSYNCER_CONFIG="$(mktemp -t vdirsyncerXXXX)"
trap 'rm -f $VDIRSYNCER_CONFIG' EXIT

cat > "$VDIRSYNCER_CONFIG" <<EOS
[general]
status_path = ~/.vdirsyncer/status/

# CARDDAV
[pair contacts]
a = carddav_local
b = carddav_remote

conflict_resolution = "b wins"

[storage carddav_local]
type = filesystem
path = ${CBK_FASTMAIL_CARDDAV_DIR}/
fileext = .vcf
encoding = utf-8

[storage carddav_remote]
type = carddav
url = https://carddav.messagingengine.com/dav/addressbooks/user/${CBK_FASTMAIL_USERNAME}/Default
auth = guess
read_only = true
username = $username
password = ${CBK_FASTMAIL_PASSWORD}
EOS

# Configure vdirsyncer to use our config file
export VDIRSYNCER_CONFIG

# Pull down CardDAV data from the remote
yes "yes" | vdirsyncer sync

# Commit changes to the git repository.
cbk-git-commit "$0" "$CBK_FASTMAIL_CARDDAV_DIR"
