#!/bin/sh
#/ Usage: cbk-pull-fastmail-imap
#/ Mirror IMAP data from Fastmail onto a local Maildir versioned by git.
set -e

cd "$(dirname "$0")/../.."
. share/cbk/cbk-config

config="$(mktemp -t offlineimaprcXXXX)"
trap 'rm -f $config' EXIT

# Write offlineimap configuration to temporary file
cat > "$config" <<EOF
[general]
accounts = Fastmail
ui = basic
fsync = false
maxconnections = 25

[Account Fastmail]
localrepository = Localhost
remoterepository = Fastmail
status_backend = plain
maxsize = 1000000000

[Repository Localhost]
type = Maildir
localfolders = $CBK_FASTMAIL_IMAP_DIR

[Repository Fastmail]
type = IMAP
remotehost = mail.messagingengine.com
remoteport = 993
remoteuser = $CBK_FASTMAIL_USERNAME
ssl = True
cert_fingerprint = $CBK_FASTMAIL_CERT_FINGERPRINT
remotepasseval = '$CBK_FASTMAIL_PASSWORD'
readonly = True
EOF

# one way sync from fastmail.com
offlineimap -o -c "$config"

# Commit changes to the git repository.
cbk-git-commit "$0" "$CBK_FASTMAIL_IMAP_DIR"
