#!/bin/sh
set -e

if [ -z "$CBK_IRCLOGS_SOURCE" ]; then
    echo "at=cbk-pull-github error=\"CBK_IRCLOGS_SOURCE not set\"" 1>&2
    exit 1
fi

# Copy the log files
rsync -avz "$CBK_IRCLOGS_SOURCE/" "$CBK_IRCLOGS_DIR/"

# Commit changes to the git repository
cbk-git-commit "$0" "$CBK_IRCLOGS_DIR"
