#!/bin/sh
#/ Usage: . cbk-config
set -e

# Add porcelain utilities to the PATH
export PATH="$(pwd)/share/cbk:$PATH"

# The root directory where all cbk data is kept
: ${CBK_ROOT_DIR:="$HOME"}

# The base directory for all cloud backups
: ${CBK_DATA_DIR:="${CBK_ROOT_DIR}/data"}

# The location of the configuration file
: ${CBK_CONFIG:="/usr/local/etc/cbk.conf"}

# List of supported sources
: ${CBK_CLOUDS="github fastmail-imap fastmail-carddav irclogs pinboard"}

if [ ! -d "$CBK_DATA_DIR" ]; then
    echo "The data directory set in CBK_DATA_DIR does not exists." 1>&2
    exit 1
fi

# The locations of the individual backup data directories
: ${CBK_FASTMAIL_IMAP_DIR:="${CBK_DATA_DIR}/fastmail-imap"}
: ${CBK_FASTMAIL_CARDDAV_DIR:="${CBK_DATA_DIR}/fastmail-carddav"}
: ${CBK_GITHUB_DIR:="${CBK_DATA_DIR}/github"}
: ${CBK_IRCLOGS_DIR:="${CBK_DATA_DIR}/irclogs"}
: ${CBK_PINBOARD_DIR:="${CBK_DATA_DIR}/pinboard"}
export CBK_FASTMAIL_IMAP_DIR \
    CBK_FASTMAIL_CARDDAV_DIR \
    CBK_GITHUB_DIR \
    CBK_IRCLOGS_DIR \
    CBK_PINBOARD_DIR

# The cache directory used by tarsnap
: ${CBK_TARSNAP_CACHE_DIR:="${CBK_ROOT_DIR}/cache"}
export CBK_TARSNAP_CACHE_DIR

# The key file used for creating the tarsnap archives
: ${CBK_TARSNAP_KEYFILE="/usr/local/etc/tarsnap.key"}
export CBK_TARSNAP_KEYFILE

# Source in configuration file.
. "$CBK_CONFIG"
