#!/bin/sh
#/ Usage: cbk-git-mirror <repository> <directory>
#/
#/ Mirror the given git URL into the given directory, setting up the destination
#/ repository if necessary before pulling in changes from the remote.
set -e

repourl="$1"
destdir="$2"

# show usage when arguments are missing
if test $# -eq 0 || test -z "$repourl" || test -z "$destdir"
then
    cat "$0" | grep '^#/' | cut -c4- 1>&2
    exit 2
fi

# perform the initial clone if the mirror doesn't exist yet
test -d "$destdir" ||
git clone -q --mirror "$repourl" "$destdir">/dev/null

# sync changes from the remote repository
git --git-dir="$destdir" fetch -ap --quiet "$repourl"

# optimize repository
cbk-git-gc "$destdir"
